# Generated by Django 4.2.4 on 2023-08-30 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_excel_db', '0012_alter_inventory_shape'),
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='import_excel_db.inventory'),
            preserve_default=False,
        ),
    ]
