# Generated by Django 4.2.5 on 2023-10-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_remove_parts_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='type',
            field=models.CharField(choices=[('buy', 'خرید'), ('produce', 'تولیدی')], default=1),
            preserve_default=False,
        ),
    ]
