# Generated by Django 4.2.5 on 2023-10-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0005_parts_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='part_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('manager', models.CharField(max_length=50)),
                ('part_type', models.CharField(choices=[('1', 'مته'), ('2', 'انگشتی'), ('3', 'مرغک'), ('4', 'برقو')])),
                ('exact_model', models.CharField(max_length=50)),
                ('partnumber', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parts.parts')),
            ],
        ),
    ]
