# Generated by Django 4.2.5 on 2023-10-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_out', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part_form',
            name='qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
