# Generated by Django 4.2.5 on 2023-10-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_out', '0002_part_form_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part_form',
            name='qty',
        ),
        migrations.AlterField(
            model_name='part_form',
            name='part_type',
            field=models.CharField(choices=[('1', 'مته'), ('2', 'انگشتی'), ('4', 'برقو'), ('3', 'مرغک')]),
        ),
    ]
