# Generated by Django 4.2.4 on 2023-08-26 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Isels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isel_name', models.CharField(max_length=50)),
                ('x_pos', models.IntegerField()),
                ('y_pos', models.IntegerField()),
                ('ori', models.FloatField(max_length=6)),
                ('part_name', models.CharField(max_length=300)),
                ('QTY', models.IntegerField()),
                ('list_update', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
