# Generated by Django 4.2.4 on 2023-08-27 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isels',
            old_name='ori',
            new_name='ori_degree',
        ),
        migrations.RenameField(
            model_name='isels',
            old_name='x_pos',
            new_name='x_pos_cm',
        ),
        migrations.RenameField(
            model_name='isels',
            old_name='y_pos',
            new_name='y_pos_cm',
        ),
    ]
