# Generated by Django 4.2.4 on 2023-08-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isels', '0002_rename_ori_isels_ori_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isels',
            name='QTY',
        ),
    ]
