# Generated by Django 4.2.4 on 2023-08-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_excel_db', '0010_remove_inventory_qty_remove_inventory_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='QTY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='brand',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='coordinate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='inventory',
            name='depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='part_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='shape',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
