# Generated by Django 4.2.4 on 2023-08-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_excel_db', '0018_inventory_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='brand',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
