# Generated by Django 4.2.4 on 2023-08-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=50)),
                ('vendor_addres', models.TextField(max_length=500)),
                ('vendor_city', models.CharField(max_length=30)),
                ('vendor_state', models.CharField(max_length=30)),
                ('vendor_products', models.CharField(max_length=120)),
            ],
        ),
    ]
