# Generated by Django 4.2.4 on 2023-08-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='vendor_phone_number',
            field=models.TextField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
