# Generated by Django 4.2.4 on 2023-08-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendors_vendor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='vendor_phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
