# Generated by Django 4.2.4 on 2023-08-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_excel_db', '0005_employee_delete_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.IntegerField()),
                ('name', models.CharField(max_length=150, null=True)),
                ('QTY', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('shape', models.CharField(choices=[('مستطیل', 'مستطیل'), ('استوانه', 'استوانه'), ('مربع', 'مربع'), ('دایره', 'دایره')])),
                ('brand', models.CharField(default='', max_length=50, null=True)),
                ('coordinate', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
