# Generated by Django 4.2.4 on 2023-08-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_excel_db', '0009_alter_inventory_qty_alter_inventory_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='QTY',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='coordinate',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='length',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='width',
        ),
    ]
