# Generated by Django 4.2.4 on 2023-08-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_excel_db', '0014_alter_inventory_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='coordinate',
            field=models.CharField(max_length=50),
        ),
    ]
