# Generated by Django 4.2.4 on 2023-08-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_excel_db', '0015_alter_inventory_coordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='shape',
            field=models.CharField(choices=[('مستطیل', 'مستطیل'), ('استوانه', 'استوانه'), ('مربع', 'مربع'), ('دایره', 'دایره')], max_length=50, null=True),
        ),
    ]
