# Generated by Django 4.2.5 on 2023-10-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_excel_db', '0019_alter_inventory_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='QTY',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
