# Generated by Django 4.2.4 on 2023-08-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_num', models.IntegerField()),
                ('part_name', models.CharField(max_length=50)),
                ('length', models.FloatField(max_length=20)),
                ('width', models.FloatField(max_length=20)),
                ('depth', models.FloatField(max_length=20)),
                ('shape', models.CharField(choices=[('مستطیل', 'مستطیل'), ('استوانه', 'استوانه'), ('مربع', 'مربع'), ('دایره', 'دایره')])),
                ('vendors', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendors.vendors')),
            ],
        ),
    ]
