# Generated by Django 4.2.5 on 2023-10-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_parts_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts',
            name='inventory',
        ),
    ]
