# Generated by Django 4.2.5 on 2023-10-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_parts_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
